package api

import (
	_ "embed"
	"net/http"
)

// openapiSpec is a hand-written OpenAPI 3.1 document rather than one
// generated by swaggo annotations (spec/10-api.md's suggested approach):
// swaggo's codegen step needs to run as part of `go generate` against a
// build toolchain this environment doesn't have configured, and a
// hand-written spec that's kept in sync with the routes in server.go is a
// reasonable substitute for the same end result — a spec a client can
// import into Postman/Insomnia or generate an SDK from.
//
//go:embed openapi.json
var openapiSpec []byte

// ServeOpenAPI serves the static OpenAPI 3.1 spec at GET /api/openapi.json.
func ServeOpenAPI(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(openapiSpec)
}
